### ISSUE TITLE
Question: How to use --exclude --ignore

### ISSUE THREAD

**Issue by udiedrichsen** [crearlink/react-doc-creator#1]
I tried a lot of things, but I dont manage to ignore folders or exclude files.

I tried for example:
--exclude 'demo.jsx' --ignore ['__tests__','patterns/templates']
--exclude demo.jsx --ignore '__tests__','patterns/templates'
--exclude demo.jsx --ignore __tests__,patterns/templates

etc.

Can add an example in your README.md?

**Comment by crearlink** [comment]
Hello Ulrich,

thank you for writing. This is my first public package and you're the first commenting!

The `--exclude` option was not working at all. It's already fixed.

You should use a regular expression there. In your case it would be `--exclude demo\.jsx`.
Since the options are normally written in `package.json`, it's necessary to escape the backslash resulting something like:

```json
"build:doc": "react-doc-creator src --exclude demo\\.jsx"
```

`--ignore` works as intended. It does admit subfolders. You should use `--ignore tests,template`

Following your suggestion I also added some use examples: https://github.com/crearlink/react-doc-creator#use-examples

I just upgraded the package to version 0.0.7

Could you please confirm whether you're now able ignore the directories and files you need to?

**Comment by udiedrichsen** [comment]
Hi,

Again, thanks a lot for this useful package. Great job with your first public package.

It works now perfect for me.
